# Generated by Django 4.2.30 on 2026-04-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='imagem',
            field=models.ImageField(upload_to='perfil/'),
        ),
    ]
